spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proyectodb?useSSL=false
    username: root
    password: admin

  http:
    multipart:
      max-file-size: -1
      max-request-size: -1

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#    show-sql: true
